name: Build Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Image
        run: |
          docker login ghcr.io --username ${{ secrets.GHCR_USER }} --password ${{secrets.GHCR_TOKEN}}
          docker build . -t ghcr.io/jenkins-x/jx-docs/jx-docs:latest -f Dockerfile.all
          docker push ghcr.io/jenkins-x/jx-docs/jx-docs:latest
